### ISSUE TITLE
allow models to weight the fit to the left tail

### ISSUE THREAD

**Issue by joethorley** [bcgov/ssdca#11]

**Comment by joethorley** [comment]
this requires a weighting scheme with fitdist(weights = ) a vector of positive integers - the question is how to get this weighting scheme...

**Comment by joethorley** [comment]
@cschwarz-stat-sfu-ca - do you know of any literature that outlines a weighting scheme we could use to weight the fit to the left tail?

**Comment by joethorley** [comment]
FWIW although fitdistrplus allows weighted fits very little functionality is implemented ie no bootstrap, gof, plots etc

**Comment by cschwarz-stat-sfu-ca** [comment]
Hmmm... The problem is trying to figure exactly what we want to do by giving more weight to the (left) tail. Presumably, we want a distribution that fits the left tail and essentially ignores what happens in the right tail so that we can get good estimates of the HC5.  

There is a large body of literature on estimating the tails of a distribution (extreme value theory) but that may not be suitable because we are not interested, e.g. in the 1000 year return period for a flood. 

If we had large sample sizes, we could estimate the HC5 empirically directly, but it is unlikely that we have sample sizes of the order of 100s of species.

With smaller sample sizes, the only way to get good estimates of tail behaviour is by fitting the entire distribution and using the fitted distribution to fit the tails. So ironically, to get estimates of tail behaviour, we need to typically fit parameters related to the location (such as the mean) and scale (such as the SD). 

We could try a crude approach and just "censor" (say the right 25% of the endpoints). Eg replace data such as
    2, 3, 4, 7, 9, 12, 17, 100
by
   2, 3, 4, 7 9+, 9+, 9+, 9+
I think fitdistrplus can deal with censored data? That may be a quick and dirty approach.

Of course there is the elephant in the room that SSD is being fit to a non-random sample of species so what does the HC5 actually mean?

**Comment by joethorley** [comment]
Yes that all makes sense.

I'll check out the censoring approach.

Yes it is rather a big elephant
